Dependencies added
DAHP-MC/Spells-Api pull request #17
Opened 2020-10-06 19:13 UTC by govindraj111

# Associated Issue: #16 

## Key Change Summary

Note: Dependency for Player Particles could not be added.
Dependencies added: ProtocolLib, Vault API, Libs Disguises, WorldGuard, WorldEdit.

2020-10-06 20:13 UTC, sirNikolai requested changes
Thanks for the contribution.
My bad for not specifying but should be valid for version `1.16.2` at least.
Some minor bits and pieces that need changing here, comments mention most of them.

The program is also failing to compile because of libs disguises not being included (as mentioned in a different comment). This should be imported through maven and not treated as a system provided resource.

2020-10-06 20:13 UTC, sirNikolai commented on pom.xml
> +            <groupId>com.github.azbh111</groupId>
This should be the dmulloy one

2020-10-07 06:15 UTC, govindraj111 commented
@sirNikolai will do that!

2020-10-07 06:54 UTC, govindraj111 commented
@sirNikolai Please review the changes!

2020-10-08 01:07 UTC, merged

2020-10-08 01:09 UTC, sirNikolai commented
This required fixes. It got merged in with more changes. In future please run locally to make sure this works (at least compiles) bore finalizing PRs.

2020-10-08 08:19 UTC, govindraj111 commented
:+1:

2020-10-15 18:26 UTC, govindraj111 commented
@sirNikolai would request you to label this PR as **hacktoberfest-accepted**

2020-10-16 02:46 UTC, govindraj111 commented
>> **Hey, an update from hactoberfest states that the PR should be labeled as ‘hacktoberfest-accepted’ by a maintainer.**
![Screenshot from 2020-10-16 08-04-27](https://user-images.githubusercontent.com/37842596/96207011-c8468b00-0f87-11eb-9d3b-fa4a7d189a50.png)
![Screenshot from 2020-10-16 08-06-57](https://user-images.githubusercontent.com/37842596/96207024-cda3d580-0f87-11eb-8bce-5a10acb2d46f.png)

>> **Please label this PR as hacktoberfest-accepted**
![hacktoberfest-label-add-gif-min](https://user-images.githubusercontent.com/37842596/96207040-d7c5d400-0f87-11eb-877e-7f2e4f683752.gif)